# Generated by Django 5.0.6 on 2026-08-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1_answer', models.IntegerField(blank=True, null=True)),
                ('question_2_answer', models.IntegerField(blank=True, null=True)),
                ('question_3_answer', models.IntegerField(blank=True, null=True)),
                ('question_4_answer', models.IntegerField(blank=True, null=True)),
                ('question_5_answer', models.IntegerField(blank=True, null=True)),
                ('question_6_answer', models.IntegerField(blank=True, null=True)),
                ('assessment_score', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(max_length=100)),
                ('team_size', models.CharField(max_length=50)),
                ('revenue', models.CharField(max_length=50)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
