# Generated by Django 5.0.6 on 2026-08-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='assessment_zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='assessment_zone_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='qualification_route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
