# Generated by Django 5.0.6 on 2026-08-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessmentsubmission_assessment_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='assessment_diagnostic_interpretation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='assessment_diagnostic_primary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='assessment_diagnostic_quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
