# Generated by Django 5.0.6 on 2026-08-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_assessmentsubmission_assessment_diagnostic_interpretation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='business_pressure_matrix',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='primary_constraint',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='secondary_bottlenecks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
