# Generated by Django 5.2.17 on 2026-08-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_assessmentsubmission_business_pressure_matrix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='booking_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='calendly_event_uri',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='calendly_invitee_uri',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
