# Generated by Django 5.0.6 on 2026-09-05 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_assessmentsubmission_booking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTAInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='BPA', max_length=50)),
                ('action', models.CharField(default='whatsapp_strategy_call', max_length=50)),
                ('status', models.CharField(default='new', max_length=30)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, max_length=2000, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cta_interactions', to='assessment.assessmentsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
