# Generated by Django 5.0.6 on 2026-09-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_ctainteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='first_landing_page',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='first_touch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='first_utm_campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='first_utm_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='first_utm_medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='first_utm_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='first_utm_term',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='last_landing_page',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='last_touch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='last_utm_campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='last_utm_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='last_utm_medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='last_utm_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='last_utm_term',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
