# Generated by Django 5.2.17 on 2026-09-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FGACohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_number', models.PositiveIntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='Asia/Dubai', help_text='Timezone for the cohort schedule (e.g. Asia/Dubai for GST)', max_length=50)),
                ('duration_weeks', models.PositiveIntegerField(default=13)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FGA Cohort',
                'verbose_name_plural': 'FGA Cohorts',
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
